# Generated by Django 3.2.4 on 2022-04-10 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        db_column="Login_id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_column="Login_username", max_length=32, unique=True
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_column="Login_password",
                        max_length=128,
                        verbose_name="password",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("farmer", "farmer"),
                            ("manager", "manager"),
                            ("worker", "worker"),
                        ],
                        db_column="Login_rank",
                        default="worker",
                        max_length=10,
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        db_column="Login_last_login",
                        null=True,
                        verbose_name="last login",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="Login_is_active",
                        default=True,
                        verbose_name="Account active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        db_column="Login_is_staff",
                        default=True,
                        verbose_name="Is staff",
                    ),
                ),
            ],
            options={
                "db_table": "Login",
                "ordering": ("username",),
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        db_column="Worker_id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        db_column="Worker_first_name",
                        max_length=127,
                        verbose_name="Worker first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_column="Worker_last_name",
                        max_length=127,
                        verbose_name="Worker last name",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        db_column="Worker_national_id",
                        max_length=32,
                        verbose_name="Worker National Identification Number",
                    ),
                ),
                (
                    "phone_no",
                    account.models.PossiblePhoneNumberField(
                        blank=True,
                        db_column="Worker_phone_no",
                        default="",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "login_id",
                    models.ForeignKey(
                        db_column="Worker_Login_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="login id",
                    ),
                ),
            ],
            options={
                "db_table": "Worker",
                "ordering": ("first_name",),
            },
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        db_column="Farmer_id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        db_column="Farmer_first_name",
                        max_length=127,
                        verbose_name="farmer first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_column="Farmer_last_name",
                        max_length=127,
                        verbose_name="Farmer last name",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        db_column="Farmer_national_id",
                        max_length=32,
                        verbose_name="Farmer National Identification Number",
                    ),
                ),
                (
                    "phone_no",
                    account.models.PossiblePhoneNumberField(
                        blank=True,
                        db_column="Farmer_phone_no",
                        default="",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "login_id",
                    models.ForeignKey(
                        db_column="Farmer_Login_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="login id",
                    ),
                ),
            ],
            options={
                "db_table": "Farmer",
                "ordering": ("first_name",),
            },
        ),
    ]
