# Generated by Django 3.2.4 on 2022-03-19 18:06

import django.db.models.deletion
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations, models

import account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        db_column="Login_id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "username",
                    models.CharField(
                        db_column="Login_username", max_length=32, unique=True
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="late joined"),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_manager", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "avatar",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        default="defaultprofile.png",
                        height_field="height",
                        null=True,
                        upload_to="user-profile-images",
                        verbose_name="Profile picture",
                        width_field="width",
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Profile Image Height"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Profile Image Width"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "Login",
                "ordering": ("username",),
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        db_column="Worker_id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        db_column="Worker_first_name",
                        max_length=127,
                        verbose_name="Worker first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_column="Worker_last_name",
                        max_length=127,
                        verbose_name="Worker last name",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        db_column="Worker_national_id",
                        max_length=32,
                        verbose_name="Worker National Identification Number",
                    ),
                ),
                (
                    "phone_no",
                    account.models.PossiblePhoneNumberField(
                        blank=True,
                        db_column="Worker_phone_no",
                        default="",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "login_id",
                    models.ForeignKey(
                        db_column="Worker_Login_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="login id",
                    ),
                ),
            ],
            options={
                "db_table": "Worker",
                "ordering": ("first_name",),
            },
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        db_column="Farmer_id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        db_column="Farmer_first_name",
                        max_length=127,
                        verbose_name="farmer first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_column="Farmer_last_name",
                        max_length=127,
                        verbose_name="Farmer last name",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        db_column="Farmer_national_id",
                        max_length=32,
                        verbose_name="Farmer National Identification Number",
                    ),
                ),
                (
                    "phone_no",
                    account.models.PossiblePhoneNumberField(
                        blank=True,
                        db_column="Farmer_phone_no",
                        default="",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "login_id",
                    models.ForeignKey(
                        db_column="Farmer_Login_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="login id",
                    ),
                ),
            ],
            options={
                "db_table": "Farmer",
                "ordering": ("first_name",),
            },
        ),
    ]
