# Generated by Django 3.2.4 on 2022-04-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputproduct",
            name="unit_rate_measurement",
            field=models.CharField(
                choices=[
                    ("KG/acre", "kilogram/acre"),
                    ("L/acre", "liter/acre"),
                    ("G/acre", "grams/acre"),
                    ("KG/ha", "kilogram/hectare"),
                    ("L/ha", "liter/hectare"),
                    ("G/hectare", "grams/hectare"),
                    ("bag/acre", "bags/acre"),
                    ("bag/hectare", "bags/hectare"),
                ],
                db_column="Input_product_unit_rate_measurement",
                default="KG/acre",
                max_length=32,
                verbose_name="Product unit rate measurement",
            ),
        ),
    ]
