# Generated by Django 3.2.4 on 2022-03-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input", "0003_auto_20220322_1433"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputproduct",
            name="desc",
            field=models.TextField(
                blank=True,
                db_column="Input_product_desc",
                verbose_name="Input product description",
            ),
        ),
    ]
