# Generated by Django 3.2.4 on 2022-03-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input", "0004_alter_inputproduct_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputcategory",
            name="desc",
            field=models.TextField(
                blank=True,
                db_column="Input_category_desc",
                verbose_name="Input Category description",
            ),
        ),
        migrations.AlterField(
            model_name="inputinventory",
            name="desc",
            field=models.TextField(
                blank=True,
                db_column="Input_Inventory_desc",
                verbose_name="Input Inventory description",
            ),
        ),
    ]
