# Generated by Django 3.2.4 on 2022-03-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input", "0005_auto_20220324_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputinventoryitem",
            name="input_product",
            field=models.ForeignKey(
                db_column="Input_Inventory_item_Input_product_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="input.inputproduct",
            ),
        ),
    ]
