# Generated by Django 3.2.4 on 2022-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input", "0007_inputinventoryitem_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputproduct",
            name="available_quantity",
            field=models.PositiveBigIntegerField(
                db_column="Input_product_available_quantity",
                default=0,
                verbose_name="Available Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="inputproduct",
            name="total_units",
            field=models.PositiveBigIntegerField(
                db_column="Input_product_total_cost",
                default=0,
                verbose_name="Product total units",
            ),
        ),
    ]
