# Generated by Django 3.2.4 on 2022-04-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0008_auto_20220406_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputproduct',
            name='available_quantity',
        ),
        migrations.AddField(
            model_name='inputproduct',
            name='available_units',
            field=models.PositiveBigIntegerField(db_column='Input_product_available_quantity', default=0, verbose_name='Available Units'),
        ),
    ]
