# Generated by Django 3.2.4 on 2022-04-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input", "0009_auto_20220406_2315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputproduct",
            name="available_units",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_column="Input_product_available_quantity",
                default=0,
                verbose_name="Available Units",
            ),
        ),
    ]
