# Generated by Django 3.2.4 on 2022-03-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, db_column='Crop_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Crop_name', max_length=127, verbose_name='Crop name')),
                ('desc', models.TextField(blank=True, db_column='Crop_desc', null=True, verbose_name='Crop description')),
                ('variety', models.CharField(blank=True, db_column='Crop_variety', max_length=127, null=True, verbose_name='Crop Variety')),
                ('maturity_duration', models.PositiveIntegerField(db_column='Crop_maturity_duration', verbose_name='Crop maturity duration')),
                ('duration_measurement', models.CharField(choices=[('WEEK', 'week(s)'), ('MONTH', 'month(s)'), ('YEAR', 'year(s)')], db_column='Crop_duration_measurement', default='WEEK', max_length=16, verbose_name='Crop maturity duration measurement')),
            ],
            options={
                'db_table': 'Crop',
            },
        ),
        migrations.CreateModel(
            name='FarmingSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, db_column='Farming_season_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Farming_season_name', max_length=64, verbose_name='Farming season name')),
                ('desc', models.TextField(blank=True, db_column='Farming_season_desc', verbose_name='Farming season description')),
                ('start_date', models.DateField(db_column='Farming_season_start_date', verbose_name='Farming season start date')),
                ('end_date', models.DateField(db_column='Farming_season_end_date', verbose_name='Farming season end date')),
                ('yields', models.PositiveIntegerField(db_column='Farming_season_yields', default=0, verbose_name="Season's yields")),
                ('yields_measurement', models.CharField(choices=[('KG/acre', 'kgs/acre'), ('KG/ha', 'kgs/hectare'), ('TONs/acre', 'tons/acre'), ('TONs/ha', 'tons/hectare'), ('BAGs/acre', 'bags/acre'), ('BAGs/ha', 'bags/hectare')], db_column='Farming_season_yields_measurement', max_length=32, verbose_name='Yields measurement')),
                ('crop', models.ForeignKey(db_column='Farming_season_Crop_id', on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farming.crop', verbose_name='Crop planted')),
                ('farm', models.ForeignKey(db_column='Farming_season_Farm_id', on_delete=django.db.models.deletion.CASCADE, to='farm.farm', verbose_name='Farm')),
            ],
            options={
                'db_table': 'Farming_season',
            },
        ),
        migrations.CreateModel(
            name='FarmingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, db_column='Farming_stage_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Farming_stage_name', max_length=64, verbose_name='Farming Stage name')),
                ('desc', models.TextField(db_column='Farming_stage_desc', verbose_name='Farming Stage description')),
                ('start_date', models.DateField(db_column='Farming_stage_start_date', verbose_name='Farming season start date')),
                ('duration', models.PositiveIntegerField(blank=True, db_column='Farming_stage_duration', verbose_name='Farm stage duration')),
                ('duration_measurement', models.CharField(blank=True, choices=[('WEEK', 'week(s)'), ('MONTH', 'month(s)')], db_column='Farming_stage_duration_measurement', max_length=32, verbose_name='Farming stage duration measurement')),
                ('farming_season', models.ForeignKey(db_column='Farming_stage_Farming_Season_id', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='farming.farmingseason', verbose_name='Current Farm stage')),
            ],
            options={
                'db_table': 'Farming_stage',
            },
        ),
    ]
