# Generated by Django 3.2.4 on 2022-04-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        db_column="Crop_id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="Crop_name", max_length=127, verbose_name="Crop name"
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        db_column="Crop_desc",
                        null=True,
                        verbose_name="Crop description",
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True,
                        db_column="Crop_variety",
                        max_length=127,
                        null=True,
                        verbose_name="Crop Variety",
                    ),
                ),
                (
                    "maturity_duration",
                    models.PositiveIntegerField(
                        db_column="Crop_maturity_duration",
                        verbose_name="Crop maturity duration",
                    ),
                ),
                (
                    "duration_measurement",
                    models.CharField(
                        choices=[
                            ("week(s)", "week(s)"),
                            ("month(s)", "month(s)"),
                            ("year(s)", "year(s)"),
                        ],
                        db_column="Crop_duration_measurement",
                        default="week(s)",
                        max_length=16,
                        verbose_name="Crop maturity duration measurement",
                    ),
                ),
            ],
            options={
                "db_table": "Crop",
            },
        ),
        migrations.CreateModel(
            name="FarmingStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        db_column="Farming_stage_id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="Farming_stage_name",
                        max_length=64,
                        verbose_name="Farming Stage name",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        db_column="Farming_stage_desc",
                        verbose_name="Farming Stage description",
                    ),
                ),
            ],
            options={
                "db_table": "Farming_stage",
            },
        ),
        migrations.CreateModel(
            name="FarmingSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        db_column="Farming_season_id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="Farming_season_name",
                        max_length=64,
                        verbose_name="Farming season name",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        db_column="Farming_season_desc",
                        verbose_name="Farming season description",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_column="Farming_season_start_date",
                        verbose_name="Farming season start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        db_column="Farming_season_end_date",
                        verbose_name="Farming season end date",
                    ),
                ),
                (
                    "yields",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="Farming_season_yields",
                        default=0,
                        verbose_name="Season's yields",
                    ),
                ),
                (
                    "yields_measurement",
                    models.CharField(
                        blank=True,
                        choices=[("KGS", "kgs"), ("TONS", "tons"), ("BAGS", "bags")],
                        db_column="Farming_season_yields_measurement",
                        default="KGS",
                        max_length=32,
                        verbose_name="Yields measurement",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        db_column="Farming_season_Crop_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crops",
                        to="farming.crop",
                        verbose_name="Crop planted",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        db_column="Farming_season_Farm_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farm.farm",
                        verbose_name="Farm",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        db_column="Farming_season_current_Farming_stage_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stages",
                        to="farming.farmingstage",
                    ),
                ),
            ],
            options={
                "db_table": "Farming_season",
            },
        ),
    ]
