# Generated by Django 3.2.4 on 2022-03-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farming", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmingseason",
            name="yields",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="Farming_season_yields",
                default=0,
                verbose_name="Season's yields",
            ),
        ),
        migrations.AlterField(
            model_name="farmingseason",
            name="yields_measurement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KG/acre", "kgs/acre"),
                    ("KG/ha", "kgs/hectare"),
                    ("TONs/acre", "tons/acre"),
                    ("TONs/ha", "tons/hectare"),
                    ("BAGs/acre", "bags/acre"),
                    ("BAGs/ha", "bags/hectare"),
                ],
                db_column="Farming_season_yields_measurement",
                max_length=32,
                verbose_name="Yields measurement",
            ),
        ),
        migrations.AlterField(
            model_name="farmingstage",
            name="desc",
            field=models.TextField(
                blank=True,
                db_column="Farming_stage_desc",
                verbose_name="Farming Stage description",
            ),
        ),
    ]
