# Generated by Django 3.2.4 on 2022-04-06 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0002_auto_20220325_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='duration_measurement',
            field=models.CharField(choices=[('week(s)', 'week(s)'), ('month(s)', 'month(s)'), ('year(s)', 'year(s)')], db_column='Crop_duration_measurement', default='week(s)', max_length=16, verbose_name='Crop maturity duration measurement'),
        ),
        migrations.AlterField(
            model_name='farmingseason',
            name='yields_measurement',
            field=models.CharField(blank=True, choices=[('KG/acre', 'kgs/acre'), ('KG/ha', 'kgs/hectare'), ('TONs/acre', 'tons/acre'), ('TONs/ha', 'tons/hectare'), ('BAGs/acre', 'bags/acre'), ('BAGs/ha', 'bags/hectare')], db_column='Farming_season_yields_measurement', default='KG/acre', max_length=32, verbose_name='Yields measurement'),
        ),
        migrations.AlterField(
            model_name='farmingstage',
            name='duration_measurement',
            field=models.CharField(blank=True, choices=[('week(s)', 'week(s)'), ('month(s)', 'month(s)')], db_column='Farming_stage_duration_measurement', max_length=32, verbose_name='Farming stage duration measurement'),
        ),
        migrations.AlterField(
            model_name='farmingstage',
            name='farming_season',
            field=models.ForeignKey(db_column='Farming_stage_Farming_Season_id', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='farming.farmingseason', verbose_name='Current Farming Season stage'),
        ),
        migrations.AlterField(
            model_name='farmingstage',
            name='start_date',
            field=models.DateField(db_column='Farming_stage_start_date', verbose_name='Farming stage start date'),
        ),
    ]
