# Generated by Django 3.2.4 on 2022-04-08 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_auto_20220406_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmingstage',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='farmingstage',
            name='duration_measurement',
        ),
        migrations.RemoveField(
            model_name='farmingstage',
            name='farming_season',
        ),
        migrations.RemoveField(
            model_name='farmingstage',
            name='start_date',
        ),
        migrations.AddField(
            model_name='farmingseason',
            name='stage',
            field=models.ForeignKey(db_column='Farming_season_current_Farming_stage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='farming.farmingstage'),
        ),
        migrations.AlterField(
            model_name='farmingseason',
            name='yields_measurement',
            field=models.CharField(blank=True, choices=[('KGS', 'kgs'), ('TONS', 'tons'), ('BAGS', 'bags')], db_column='Farming_season_yields_measurement', default='KGS', max_length=32, verbose_name='Yields measurement'),
        ),
    ]
