# Generated by Django 3.2.4 on 2022-04-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soil",
            name="status",
            field=models.CharField(
                choices=[("healthy", "healthy"), ("unhealthy", "unhealthy")],
                db_column="Soil_status",
                max_length=64,
                verbose_name="Soil status",
            ),
        ),
    ]
