# Generated by Django 3.2.4 on 2022-04-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmtask",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="farmtask",
            name="expected_expenses_price_amount",
        ),
        migrations.AddField(
            model_name="farmtask",
            name="expected_expenses",
            field=models.DecimalField(
                db_column="Farm_Task_expected_expenses",
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Farm Task expected expenses",
            ),
        ),
    ]
