# Generated by Django 3.2.4 on 2022-03-25 17:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input", "0005_auto_20220324_1245"),
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farmtask",
            old_name="objective",
            new_name="objectives",
        ),
        migrations.AlterField(
            model_name="farmtask",
            name="notes",
            field=tinymce.models.HTMLField(
                blank=True, db_column="Farm_Task_notes", verbose_name="Farm Task notes"
            ),
        ),
        migrations.AlterField(
            model_name="farmtask",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                db_column="Farm_Task_Input_product_id",
                to="input.InputProduct",
                verbose_name="Farm Task product to use",
            ),
        ),
        migrations.AlterField(
            model_name="farmtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("Ongoing", "ongoing"),
                    ("complete", "complete"),
                    ("cancelled", "cancelled"),
                ],
                db_column="Farm_Task_status",
                default="pending",
                max_length=64,
                verbose_name="Farm Task status",
            ),
        ),
    ]
