# Generated by Django 3.2.4 on 2022-03-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_auto_20220325_2058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmtask",
            name="deadline",
            field=models.DateField(
                db_column="Farm_Task_deadline", verbose_name="Farm Task end date"
            ),
        ),
        migrations.AlterField(
            model_name="farmtask",
            name="start_date",
            field=models.DateField(
                db_column="Farm_Task_start_date", verbose_name="Farm Task start date"
            ),
        ),
    ]
